#!/usr/bin/env bash
# fetch_apple_secrets.sh
#
# Pulls Apple Developer credentials from Infisical into the calling process env.
# This is the only place that talks to Infisical — the signing/notarizing scripts
# downstream read env vars only, so we can swap the secret backend later.
#
# Required Infisical secrets (one Apple Developer Program account serves all repos):
#   APPLE_TEAM_ID                       10-char team id, e.g. "ABCDE12345"
#   APPLE_DEVELOPER_ID_P12_BASE64       base64-encoded .p12 (Developer ID Application cert)
#   APPLE_DEVELOPER_ID_P12_PASSWORD     password for the .p12
#   APPLE_NOTARIZATION_ISSUER_ID        App Store Connect API issuer UUID
#   APPLE_NOTARIZATION_KEY_ID           App Store Connect API key id, e.g. "ABC1234XYZ"
#   APPLE_NOTARIZATION_KEY_P8_BASE64    base64-encoded .p8 private key
#
# Optional (per-repo, can come from GH secrets fallback):
#   APPLE_BUNDLE_ID                     e.g. "app.phenotype.omniroute"
#   APPLE_SIGNING_IDENTITY              SHA-1 of cert, or "Developer ID Application: Foo (TEAMID)"
#
# Usage:
#   fetch_apple_secrets.sh [--project-id UUID] [--env dev|staging|prod] [--path /apple]
#
# Exit codes:
#   0  success
#   2  missing required env or CLI
#   1  network / Infisical error

set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage: fetch_apple_secrets.sh [--project-id UUID] [--env dev|staging|prod] [--path /apple]

Reads:
  INFISICAL_TOKEN        machine identity service token (required)
  INFISICAL_PROJECT_ID   project UUID (or pass --project-id)
  INFISICAL_ENV          dev|staging|prod (or pass --env)
  INFISICAL_PATH         secret path in Infisical (default: /apple)

Writes (to current shell via `source` or to env file if --env-file):
  APPLE_TEAM_ID, APPLE_DEVELOPER_ID_P12_BASE64, APPLE_DEVELOPER_ID_P12_PASSWORD,
  APPLE_NOTARIZATION_ISSUER_ID, APPLE_NOTARIZATION_KEY_ID, APPLE_NOTARIZATION_KEY_P8_BASE64
EOF
}

project_id="${INFISICAL_PROJECT_ID:-}"
env_name="${INFISICAL_ENV:-}"
secret_path="${INFISICAL_PATH:-/apple}"
env_file=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --project-id) project_id="$2"; shift 2 ;;
    --env)        env_name="$2"; shift 2 ;;
    --path)       secret_path="$2"; shift 2 ;;
    --env-file)   env_file="$2"; shift 2 ;;
    -h|--help)    usage; exit 0 ;;
    *)            echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

# Fall back to known default project id (matches fleet-ops workflow)
project_id="${project_id:-8efe392e-56a6-4c3c-89f9-8141183dd7e8}"

if [[ -z "${INFISICAL_TOKEN:-}" ]]; then
  echo "INFISICAL_TOKEN env var is required." >&2
  exit 2
fi

if [[ -z "$env_name" ]]; then
  # Default: prod on main/master, staging on staging branch, dev elsewhere
  case "${GITHUB_REF:-}" in
    refs/heads/main|refs/heads/master) env_name="prod" ;;
    refs/heads/staging)                env_name="staging" ;;
    *)                                 env_name="dev" ;;
  esac
fi

if ! command -v infisical >/dev/null 2>&1; then
  echo "infisical CLI not on PATH. Install via: brew install infisical" >&2
  exit 2
fi

# Infisical CLI: `infisical export --projectId X --env Y --path Z --format dotenv`
export_args=(
  export
  --projectId "$project_id"
  --env "$env_name"
  --path "$secret_path"
  --format dotenv
)

# If secrets come from GitHub Actions secrets, prefer those (already injected as env vars).
# We only fetch from Infisical the keys that are NOT already in the environment.
keys=(
  APPLE_TEAM_ID
  APPLE_DEVELOPER_ID_P12_BASE64
  APPLE_DEVELOPER_ID_P12_PASSWORD
  APPLE_NOTARIZATION_ISSUER_ID
  APPLE_NOTARIZATION_KEY_ID
  APPLE_NOTARIZATION_KEY_P8_BASE64
)

# `infisical export` returns ALL secrets at the path. Parse dotenv output and only
# set keys that aren't already in the env, so GitHub repo secrets take precedence.
infisical_output="$(infisical "${export_args[@]}" 2>&1)" || {
  echo "infisical export failed: $infisical_output" >&2
  exit 1
}

declare -A fetched
while IFS='=' read -r k v; do
  # strip optional leading "export " and surrounding quotes
  k="${k#export }"
  v="${v%\"}"
  v="${v#\"}"
  case "$k" in APPLE_*) fetched["$k"]="$v" ;; esac
done <<< "$infisical_output"

# Normalize key naming: helios-cli uses APPLE_NOTARIZATION_KEY_P8 (no _BASE64 suffix
# for raw form), and signing scripts read it as base64. Keep _BASE64 form when
# fetched from Infisical; downstream scripts decode.
# Map alias: if APPLE_NOTARIZATION_KEY_P8 fetched, expose both forms.
[[ -n "${fetched[APPLE_NOTARIZATION_KEY_P8_BASE64]:-}" && -z "${APPLE_NOTARIZATION_KEY_P8:-}" ]] && \
  export APPLE_NOTARIZATION_KEY_P8="${fetched[APPLE_NOTARIZATION_KEY_P8_BASE64]}"

if [[ -n "$env_file" ]]; then
  {
    echo "# Generated by fetch_apple_secrets.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source: Infisical ${project_id}/${env_name}${secret_path}"
    for k in "${keys[@]}"; do
      v="${fetched[$k]:-${!k:-}}"
      [[ -n "$v" ]] && printf '%s=%q\n' "$k" "$v"
    done
  } > "$env_file"
  chmod 600 "$env_file"
  echo "Wrote $env_file (mode 600)" >&2
else
  for k in "${keys[@]}"; do
    if [[ -z "${!k:-}" && -n "${fetched[$k]:-}" ]]; then
      export "$k=${fetched[$k]}"
    fi
  done
fi

# Verify all required keys resolved
missing=0
for k in "${keys[@]}"; do
  if [[ -z "${!k:-}" ]]; then
    echo "Required key $k was not found in Infisical ${env_name}${secret_path} and not provided in env." >&2
    missing=1
  fi
done

exit "$missing"
